# Generated by Django 5.1.4 on 2026-04-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('stage', models.CharField(default='queued', max_length=64)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('limit', models.PositiveIntegerField(default=10)),
                ('max_pages', models.PositiveIntegerField(default=3)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_jobs', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
