# Generated by Django 5.1.4 on 2026-04-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookinsight',
            constraint=models.UniqueConstraint(fields=('book', 'insight_type'), name='unique_insight_type_per_book'),
        ),
    ]
